# Generated by Django 4.0.5 on 2022-06-03 07:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'allergy',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'drink_category',
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kcal', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('saturated_fat', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('caffeine', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'nutrition',
            },
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('alle', models.ManyToManyField(related_name='allergy_name', to='product.allergy')),
                ('cat', models.ManyToManyField(related_name='category_name', to='product.category')),
                ('nut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.nutrition')),
            ],
            options={
                'db_table': 'drink',
            },
        ),
    ]
